# Site settings
title: Andrea Gentili
header-img: img/home-bg.jpg
email: info@gentiliandrea.it
description: "Sito personale di Andrae Gentili: Programmatore informatico e giocoliere"
baseurl: ""
url: "http://gentiliandrea.it"
github_username:  bluvertigo
facebook_username:  gentili

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
